const EVENTS_HAS_ERRORED = 'EVENTS_HAS_ERRORED'
const EVENTS_ARE_LOADING = 'EVENTS_ARE_LOADING'
const EVENTS_FETCH_DATA_SUCCESS = 'EVENTS_FETCH_DATA_SUCCESS'
const EVENT_FETCH_DATA_SUCCESS = 'EVENT_FETCH_DATA_SUCCESS'

export {
  EVENTS_HAS_ERRORED,
  EVENTS_ARE_LOADING,
  EVENTS_FETCH_DATA_SUCCESS,
  EVENT_FETCH_DATA_SUCCESS
}