const USERS_HAS_ERRORED = 'USERS_HAS_ERRORED'
const USERS_ARE_LOADING = 'USERS_ARE_LOADING'
const USERS_FETCH_DATA_SUCCESS = 'USERS_FETCH_DATA_SUCCESS'
const USER_FETCH_DATA_SUCCESS = 'USER_FETCH_DATA_SUCCESS'


export {
  USERS_HAS_ERRORED,
  USERS_ARE_LOADING,
  USERS_FETCH_DATA_SUCCESS,
  USER_FETCH_DATA_SUCCESS
}