const PHOTOS_HAS_ERRORED = 'PHOTOS_HAS_ERRORED'
const PHOTOS_ARE_LOADING = 'PHOTOS_ARE_LOADING'
const PHOTOS_FETCH_DATA_SUCCESS = 'PHOTOS_FETCH_DATA_SUCCESS'
const PHOTO_FETCH_DATA_SUCCESS = 'PHOTO_FETCH_DATA_SUCCESS'


export {
  PHOTOS_HAS_ERRORED,
  PHOTOS_ARE_LOADING,
  PHOTOS_FETCH_DATA_SUCCESS,
  PHOTO_FETCH_DATA_SUCCESS
}