const CURRENT_USER_LOGIN_IS_LOADING = "CURRENT_USER_LOGIN_IS_LOADING";
const CURRENT_USER_LOGIN_HAS_ERRORED = "CURRENT_USER_LOGIN_HAS_ERRORED";
const CURRENT_USER_IS_LOGGED_IN = "CURRENT_USER_IS_LOGGED_IN";
const CURRENT_USER_FETCH_DATA_SUCCESS = "CURRENT_USER_FETCH_DATA_SUCCESS";

export {
  CURRENT_USER_LOGIN_IS_LOADING,
  CURRENT_USER_LOGIN_HAS_ERRORED,
  CURRENT_USER_IS_LOGGED_IN,
  CURRENT_USER_FETCH_DATA_SUCCESS
};
